#!/usr/bin/env python3
"""Executes Lua chunks in a running REAPER instance via the claude_bridge protocol.

The Python implementation ensures standard UTF-8 encoding without Byte Order Marks (BOM),
preventing PARSE_ERROR failures associated with PowerShell 5.1 output formats. The script
accepts input via command line argument, file, or stdin.

    python bridge.py --code 'return reaper.GetAppVersion()'
    echo 'return 1+1' | python bridge.py
    python bridge.py --lua-file cmd.lua.tmp --timeout 240

Exit code is non-zero when PARSE_ERROR or RUNTIME_ERROR occurs.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
import uuid
from pathlib import Path

# These paths cover standard REAPER installation directories across platforms.
# The active installation contains the claude_bridge subdirectory.
RESOURCE_ROOTS = (
    Path(os.environ.get("APPDATA", "")) / "REAPER",
    Path.home() / "Library" / "Application Support" / "REAPER",
    Path.home() / ".config" / "REAPER",
)

STALE_HEARTBEAT_SEC = 60

# The listener polls every 0.15s, so a slower client poll only adds latency.
POLL_SEC = 0.05

# Appended to the chunk as a trailing comment so the listener can echo it back.
# It goes last to leave the line numbers of the caller's code, and therefore of
# any error message, unchanged.
ID_MARKER = "--@claude-bridge-id:"


def find_bridge_dir(explicit: str | None) -> Path:
    if explicit:
        d = Path(explicit)
        if not d.is_dir():
            raise SystemExit(f"Bridge directory does not exist: {d}")
        return d

    env = os.environ.get("REAPER_BRIDGE_DIR")
    if env and Path(env).is_dir():
        return Path(env)

    for root in RESOURCE_ROOTS:
        candidate = root / "claude_bridge"
        if candidate.is_dir():
            return candidate

    raise SystemExit(
        "Bridge directory not found.\n"
        "Ensure REAPER is running with claude_bridge.lua active, "
        "or specify --bridge-dir for portable installations."
    )


def read_lua(args) -> str:
    if args.code:
        return args.code
    if args.lua_file:
        p = Path(args.lua_file)
        if not p.is_file():
            raise SystemExit(f"Lua file not found: {p}")
        # The utf-8-sig encoding ensures any Byte Order Marks introduced by
        # external tools are removed prior to REAPER execution.
        return p.read_text(encoding="utf-8-sig")
    data = sys.stdin.read()
    if not data.strip():
        raise SystemExit("No Lua supplied.")
    return data


def main() -> int:
    ap = argparse.ArgumentParser(description="Execute Lua inside REAPER.")
    ap.add_argument("--code", help="Lua source to run.")
    ap.add_argument("--lua-file", help="File containing the Lua source.")
    ap.add_argument("--bridge-dir", help="Override the bridge directory.")
    ap.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="Seconds to wait for a result. Certain REAPER operations block execution.",
    )
    ap.add_argument("--quiet", action="store_true", help="Suppress the timing output.")
    args = ap.parse_args()

    lua = read_lua(args)
    bridge = find_bridge_dir(args.bridge_dir)

    cmd = bridge / "cmd.lua"
    out = bridge / "out.txt"
    status = bridge / "status.txt"

    # Status file modification time provides listener state verification to
    # prevent unnecessary timeout waits.
    if status.is_file():
        age = time.time() - status.stat().st_mtime
        if age > STALE_HEARTBEAT_SEC:
            print(
                f"Warning: Bridge heartbeat is {age:.0f}s old. Continuing execution.",
                file=sys.stderr,
            )

    if cmd.exists():
        print(
            "Warning: cmd.lua exists. Previous command unconsumed.",
            file=sys.stderr,
        )

    # Timestamp evaluation ensures the script reads only new output data
    # generated by the current command.
    before = out.stat().st_mtime_ns if out.exists() else -1

    # A fresh timestamp alone does not prove the output belongs to this command.
    # A second client starting while this command runs reads whichever result
    # lands first, so both callers receive the same answer. The listener echoes
    # this token back, and any result carrying a different one is skipped.
    token = uuid.uuid4().hex[:12]
    payload = lua.rstrip("\n") + "\n" + ID_MARKER + token + "\n"

    # Atomic file replacement prevents REAPER from polling partially written data.
    tmp = bridge / "cmd.lua.partial"
    tmp.write_text(payload, encoding="utf-8", newline="\n")
    os.replace(tmp, cmd)

    start = time.monotonic()
    result = None
    while time.monotonic() - start < args.timeout:
        if out.exists():
            stamp = out.stat().st_mtime_ns
            if stamp > before:
                text = out.read_text(encoding="utf-8", errors="replace")
                if text.startswith("@id:"):
                    header, _, rest = text.partition("\n")
                    if header[len("@id:"):].strip() == token:
                        result = rest
                        break
                    # Another client's result. Keep waiting for this one.
                    before = stamp
                else:
                    # A listener from before id correlation, or a hand-written
                    # cmd.lua. Accept the result as this command's output.
                    result = text
                    break
        time.sleep(POLL_SEC)

    if result is None:
        if cmd.exists():
            # Unprocessed commands must be removed to prevent unintended delayed
            # execution on subsequent REAPER launches.
            try:
                cmd.unlink()
            except OSError:
                pass
            raise SystemExit(
                f"Command withdrawn. Bridge timeout after {args.timeout:.0f}s."
            )
        raise SystemExit(
            f"Timeout after {args.timeout:.0f}s waiting for out.txt."
        )

    if not args.quiet:
        print(f"Execution time: {time.monotonic() - start:.1f}s")
    print(result)

    return 1 if result.startswith(("PARSE_ERROR", "RUNTIME_ERROR")) else 0


if __name__ == "__main__":
    sys.exit(main())
